server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: ip-location-service
  datasource:
    url: jdbc:mysql://39.97.174.238:3306/ipaddess?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ipaddess
    password: ipaddess
    driver-class-name: com.mysql.cj.jdbc.Driver
  webflux:
    timeout: 5000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

ip2region:
  xdb:
    path: ip2region.xdb

logging:
  level:
    com.nsc.ipfind: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  health:
    db:
      enabled: false

jwt:
  secret: MySuperSecretKey_2025!@#$%^&*()
  expiration: 86400  # 24???????
